name: update-dependencies
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 6 * * 1"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - id: update
        uses: DeterminateSystems/update-flake-lock@v23
        with:
          path-to-flake-dir: "dot_config/home-manager/"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - name: Merge
        run: gh pr merge --auto "${{ steps.update.outputs.pull-request-number }}" --rebase
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
        if: ${{ steps.update.outputs.pull-request-number != '' }}
